[versions]
# Gradle
#noinspection UnusedVersionCatalogEntry
android-minSdk = "23"
#noinspection UnusedVersionCatalogEntry
android-targetSdk = "37"
#noinspection UnusedVersionCatalogEntry
android-compileSdk = "37"
#noinspection UnusedVersionCatalogEntry
android-buildToolsVersion = "37.0.0"

desugar_jdk_libs = "2.1.5"
coreKtx = "1.19.0"
appcompat = "1.8.0"
kotlinxSerializationJson = "1.11.0"
kotlinxDatetime = "0.8.0"
compose-bom = "2026.09.00"
activityCompose = "1.13.0"

# Plugins
agp = "9.4.1"
kotlin = "2.4.20"

[libraries]
# Java 8+ API Desugaring Support
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }

core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }

# Jetpack Compose
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }


[bundles]
sample-essentials = ["core-ktx", "appcompat", "kotlinx-serialization-json", "kotlinx-datetime"]
sample-compose = ["compose-ui", "compose-material3", "compose-ui-tooling-preview", "compose-ui-tooling", "activity-compose"]
library-essentials = ["kotlinx-serialization-json", "kotlinx-datetime"]
library-compose = ["compose-ui", "compose-material3"]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
maven-publish = { id = "maven-publish" }